name: Model Architecture Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Set up virtual environment
      run: |
        python -m pip install --upgrade pip
        python -m venv venv
        source venv/bin/activate
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run architecture tests
      run: |
        source venv/bin/activate
        pytest test_model.py::test_parameter_count test_model.py::test_batch_normalization_usage test_model.py::test_dropout_usage test_model.py::test_gap_vs_fc_usage -v